we-like-parsers/pegen

- src/pegen/grammar_parser.py
- src/pegen/metagrammar.gram
- tests/test_pegen.py
Currently for annotations we can only use either a normal name (like `expr`) or a name followed by star (`expr_ty*`), though at least for python, type annotations are a bit more broad. Some examples;
```
start[ast.mod]: statements
strings[List[str]]: STRING+
```
These are currently unsupported, so what this PR does is actually unifies the annotation syntax with the mini-action grammar. And opens up the possibility of the using any sort of expression as types (also includes a little bugfix that allows you to create empty dictionary on the action part)
> Generalize annotation support with actions

- src/pegen/python_generator.py
This allows to use Python formatting based on curly braces without having to double all curly braces.
> Do not format subheader

- docs/grammar.md
- src/pegen/python_generator.py
The use of non default name leads to a broken `if __name__ == __main__` section before this patch.
> Format the trailer section with the parser class name 

- src/pegen/parser_generator.py
For a Python parser we do not need to count keywords.
> Remove keyword

- src/pegen/parser.py
This is used for error reporting in the Python parser. I amunsure where to document this feature.
> Add tracking to know if we are in a recursive rule

- docs/grammar.md
- src/pegen/parser.py
- src/pegen/parser_generator.py
- src/pegen/python_generator.py
- tests/test_pegen.py
This is used once in the Python parser for error reporting.
> Add a special SOFT_KEYWORD rule allowing to match any soft keyword

- docs/grammar.md
- src/pegen/parser.py
- src/pegen/python_generator.py
- tests/test_pegen.py
- tests/utils.py
If the parsing fails, we immediately raise an error built using `make_syntax_error`
> Add support for Forced grammar node in the parser generator

- docs/grammar.md
- src/pegen/python_generator.py
- tests/test_pegen.py
The main motivation for this is to get accurate coverage reports for rules used to generate custom syntax errors
> Add a special UNREACHABLE action for rule that never execute their action

- docs/grammar.md
- src/pegen/python_generator.py
- src/pegen/tokenizer.py
- tests/test_pegen.py
- tests/test_tokenizer.py
This adds support for LOCATIONS in actions, which leads the parser to track linenos and col offsets for rules making use of it. We provide a way to customize how LOCATIONS is replaced in the generated parser.
> Add locations tracking inspired by the CPython implementation

- src/pegen/python_generator.py
- tests/test_pegen.py
Alt using an invalid rule with no action should be marked automatically unreachable since their action will never be run. However previously we were marking as unreachable the alternative of invalid rules which is usually not useful and can be quite surprising for invalid_ helpers.
I noticed this issue while working on cleaning up the Python parser.
> Fix implicit handling of unreachable

- docs/grammar.md
In particular, we describe in more details when it is automatically inserted and when one may want to insert it manually. Follow up to #26
> docs: clarify documentation of UNREACHABLE

- data/python.gram
- tests/python_parser/test_syntax_error_handling.py
Add the missing tests for the new error rules and add a missing entry in invalid_expression to actually use invalid_legacy_expression
> python.gram: fix handling of legacy expression and add tests

- data/python.gram
- tests/python_parser/test_syntax_error_handling.py
cf https://github.com/python/cpython/commit/b2f68b190035540872072ac1d2349e7745e85596
> python.gram: stricter rule for trailing comma in import

- src/pegen/python_generator.py
- tests/test_pegen.py
Fixes #40 by adding `sorted(...)` as suggested previously.
I could use some guidance for writing tests.
> Sort KEYWORDS for consistent output ordering

- scripts/grammar_grapher.py
Sync with already-merged PR on cpython: https://github.com/python/cpython/pull/31704
> Update grammar_grapher with the new forced (&&) directive

- data/python.gram
- docs/grammar.rst
- src/pegen/parser.py
- src/pegen/python_generator.py
- tests/python_parser/test_syntax_error_handling.py
- tests/python_parser/test_unsupported_syntax.py
This attempts to mimic CPython behavior by calling invalid rule only in a second pass to speed up parsing on the happy path. It also includes changes https://github.com/python/cpython/commit/390459de6db1e68b79c0897cc88c0d562693ec5c to avoid calling invalid rules from within without invalid rules.
~~With those changes, I thought I would be able to get rid of having both immediate and deferred raising of exceptions (store_ vs raise_) since looking at CPython it looks to me as if as soon as an exception is reported the parser exits. This fast exit is controlled by the error_indicator attribute on the parser state. However I hit one issue when enabling direct raising in invalid rules (so in CPython terms when looking for details about a syntax error):
`f(i for i in range(10))` fails to parse …
> Delayed error inspection

- data/python.gram
- tests/python_parser/test_syntax_error_handling.py
See https://github.com/python/cpython/commit/e5f13ce5b48b551c09fdd0faeafa6ecf860de51c
I will try to add validation of the line and offsets values in the tests but maybe not before next week.
> python.gram: reflect changes in cpython

- data/python.gram
- tests/python_parser/test_syntax_error_handling.py
This is based on #41 but add the changes from:
- bpo45716
- bpo45764
- bpo45727 (except for the fact it triggers only inside parenthesis for Python 3.11)
- bpo45450
- bpo46836
With this pegen will be up to date on syntax error reporting with 3.11
After the 3.11 beta freeze we can add support for `except *` and PEP 646 and we will be up to date with 3.11 grammar
> Improved syntax error

- .github/workflows/publish.yml
- .github/workflows/test.yml
- tests/python_parser/test_syntax_error_handling.py
And fix the one broken test on 3.10.5. Setuptools-scm complains but appear to work so I won't touch the fetch.
> Cis: use newer actions (setup-python, checkout, cache)

- releasenotes.rst
- src/pegen/tokenizer.py
- tests/test_tokenizer.py
Fixes #76 
This PR fixes an issue where `tokenizer` returns the empty string for the last line if no NEWLINE exists at the end of the source.
Python's `tokenize` module injects a NEWLINE if the source does not end with one. The injected token has the empty string for its `line` but Pegen's tokenizer remembers that empty string as the content of the last line of the source.
Since source does not change over tokenization, once `self._lines[i]` is set for some `i`, it does not need to be set again with later tokens. I added a check to only update `self._lines` only if `tok.start[0]` is not set. With this change, `NEWLINE` injected by the `tokenize` module will not override `self._lines` with the empty string.
I also added a test case for this change.
> Fix empty last line returned by tokenizer

- data/Tokens
- src/pegen/grammar_parser.py
- src/pegen/metagrammar.gram
- src/pegen/parser.py
- src/pegen/python_generator.py
As pointed out in #93, in Python 3.12 the PEP 701 changes to f-string tokenization cause Pegen to fail on grammars which contain f-strings in their actions (such as the Python grammar). This PR adds support for the new tokens to Pegen and changes the metagrammar to restore f-string support under 3.12 (while preserving support under older versions of Python).
Two things this PR does not currently do:
- Fix broken tests under 3.12. I'm getting 28 failures currently, but as far as I can tell they don't have to do with the changes in this PR and are rather caused by other differences in the 3.12 tokenizer/parser. I can try to fix these later, but any help would be appreciated!
- Update the example Python grammar (`data/python.gram`) for 3.12.
> Support Python 3.12 f-strings in grammar actions

- data/python.gram
- tests/python_parser/data/fstrings.py
There seems to be an fstring case that is incorrect with the current Python grammar. I've added a case to fstrings.py to highlight the behavior. I think the issue is an unnecessary encode in the `fstring_format_spec` rule, so I removed that, but I'm not sure if that has other implications so I would appreciate any feedback.
> Added fstring Test Case and Potential Fix

- data/python.gram
- src/pegen/parser_generator.py
- src/pegen/python_generator.py
- tests/python_parser/conftest.py
- tests/python_parser/test_ast_parsing.py
- tests/python_parser/test_syntax_error_handling.py
- tests/python_parser/test_unsupported_syntax.py
- Change `invalid_arguments` rules to follow latest Python error message https://github.com/python/cpython/pull/117465
- Fix lint issues
- Fix typos https://github.com/python/cpython/pull/120720
[Original message] Just out of curiosity, will pegen release a minor version based on the change? I'm fixing the spell check error of a project that inherits ParserGenerator.
> Fix typo and broken test cases

- .github/workflows/test.yml
- data/python.gram
- pyproject.toml
This PR makes the test suite pass under Python 3.13: the only change required is removing a use of the `ASYNC` token in `data/python.gram` (that token no longer exists in Python 3.13). While I was at it I added 3.13 to the CI matrix and updated the Trove classifiers to declare support for Python 3.8-3.13.
I have not fixed the corresponding issue in `data/fullpy.gram` as that grammar has other issues preventing it from working anyway. Nor have I removed `ASYNC` or `AWAIT` from `data/Tokens` since those tokens could still be created when using older versions of Python (and as far as I can tell the file is not used by anything except a broken part of the `show_parse.py` script).
> Support Python 3.13
